import { Injectable } from '@angular/core';
import { User } from './user.interface';

@Injectable({
  providedIn: 'root',
})
export class UserService {

  userTemplateArray: Array<User>;

  constructor() {
    this.userTemplateArray = this.getAllUsers();
  }

  getAllUsers(): Array<User> {
    return [{
      'id': 1,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 2,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 3,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 4,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 5,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 6,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 7,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 8,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 9,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 10,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 11,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 12,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 13,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 14,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 15,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 16,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 17,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 18,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 19,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 20,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 21,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 22,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 23,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 24,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 25,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 26,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 27,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 28,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 29,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 30,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 31,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 32,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 33,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 34,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 35,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 36,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 37,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 38,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 39,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 40,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 41,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 42,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 43,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 44,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 45,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 46,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 47,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 48,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 49,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 50,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 51,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 52,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 53,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 54,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 55,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 56,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 57,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 58,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 59,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 60,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 61,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 62,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 63,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 64,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 65,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 66,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 67,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 68,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 69,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 70,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 71,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 72,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 73,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 74,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 75,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 76,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 77,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 78,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 79,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 80,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 81,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 82,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 83,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 84,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 85,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 86,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 87,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 88,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 89,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 90,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 91,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 92,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 93,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 94,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Active',
    }, {
      'id': 95,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Active',
    }, {
      'id': 96,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }, {
      'id': 97,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Teacher',
      'status': 'Pending',
    }, {
      'id': 98,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Pending',
    }, {
      'id': 99,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Parent',
      'status': 'Pending',
    }, {
      'id': 100,
      'name': 'John Doe',
      'email': 'john.doe@gmail.com',
      'role': 'Student',
      'status': 'Active',
    }];
  }
}
