export const ROUTER_UTILS = {
  config: {
    base: {
      root: '',
      home: 'admin-dashboard',
    },
    auth: {
      root: 'auth',
      signIn: 'sign-in',
      signUp: 'sign-up',
      forgotPassword: 'forgot-password',
      forgotPasswordEmailSent: 'forgot-password-email-sent',
      passwordReset: 'password-reset',
      passwordResetFailed: 'password-reset-failed',
      passwordResetSucceeded: 'password-reset-succeeded',
    },
    cms: 'cms',
    videos: 'videos',
    billing: 'billing',
    reports: 'reports',
    accounting: 'accounting',
    users: {
      root: 'users',
      usersList: 'users-list',
      invitation: 'invitation',
      onlineRequest: 'online-request',
      documents: 'documents',
      archive: 'archive',
    },
    school: {
      subjects: 'subjects',
      studentGroups: 'student-groups',
      classRooms: 'class-rooms',
      calendar: 'calendar',
      tuitionTerms: 'tuition-terms',
    },
    settings: {
      root: 'settings',
      account: 'account',
      appearance: 'appearance',
      billing: 'billing',
      blockedUsers: 'blocked-users',
      notifications: 'notifications',
      security: 'security',
      securityLog: 'security-log',
    },
    user: {
      root: 'user',
      overview: 'overview',
      profile: ':username',
    },
    errorResponse: {
      notFound: '404',
    },
  },
};
