import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeResourceUrl } from "@angular/platform-browser";
import { MatIconRegistry } from "@angular/material/icon";


@NgModule({
  declarations: [],
  imports: [
    CommonModule
  ]
})
export class OtherIconsModule {
  private path = "./assets/icons/other";

  constructor(
    private domSanitizer: DomSanitizer,
    public matIconRegistry: MatIconRegistry ) {

    this.matIconRegistry
      .addSvgIcon("airplane", this.setPath(`${this.path}/airplane.svg`))
      .addSvgIcon("anchor", this.setPath(`${this.path}/anchor.svg`))
      .addSvgIcon("awards", this.setPath(`${this.path}/awards.svg`))
      .addSvgIcon("band-aid", this.setPath(`${this.path}/band-aid.svg`))
      .addSvgIcon("bee", this.setPath(`${this.path}/bee.svg`))
      .addSvgIcon("bitbucket", this.setPath(`${this.path}/bitbucket.svg`))
      .addSvgIcon("block", this.setPath(`${this.path}/block.svg`))
      .addSvgIcon("bowl", this.setPath(`${this.path}/bowl.svg`))
      .addSvgIcon("boy", this.setPath(`${this.path}/boy.svg`))
      .addSvgIcon("briefcase", this.setPath(`${this.path}/briefcase.svg`))
      .addSvgIcon("browse", this.setPath(`${this.path}/browse.svg`))
      .addSvgIcon("brush", this.setPath(`${this.path}/brush.svg`))
      .addSvgIcon("calibrate", this.setPath(`${this.path}/calibrate.svg`))
      .addSvgIcon("cap", this.setPath(`${this.path}/cap.svg`))
      .addSvgIcon("card-clubs", this.setPath(`${this.path}/card-clubs.svg`))
      .addSvgIcon("card-diamonds", this.setPath(`${this.path}/card-diamonds.svg`))
      .addSvgIcon("card-hearts", this.setPath(`${this.path}/card-hearts.svg`))
      .addSvgIcon("card-spades", this.setPath(`${this.path}/card-spades.svg`))
      .addSvgIcon("carousel", this.setPath(`${this.path}/carousel.svg`))
      .addSvgIcon("chart", this.setPath(`${this.path}/chart.svg`))
      .addSvgIcon("clapper-board", this.setPath(`${this.path}/clapper-board.svg`))
      .addSvgIcon("close", this.setPath(`${this.path}/close.svg`))
      .addSvgIcon("coffee", this.setPath(`${this.path}/coffee.svg`))
      .addSvgIcon("community", this.setPath(`${this.path}/community.svg`))
      .addSvgIcon("components", this.setPath(`${this.path}/components.svg`))
      .addSvgIcon("copyright", this.setPath(`${this.path}/copyright.svg`))
      .addSvgIcon("cross", this.setPath(`${this.path}/cross.svg`))
      .addSvgIcon("crown", this.setPath(`${this.path}/crown.svg`))
      .addSvgIcon("dark-mode", this.setPath(`${this.path}/dark-mode.svg`))
      .addSvgIcon("debug", this.setPath(`${this.path}/debug.svg`))
      .addSvgIcon("dice-1", this.setPath(`${this.path}/dice-1.svg`))
      .addSvgIcon("dice-2", this.setPath(`${this.path}/dice-2.svg`))
      .addSvgIcon("dice-3", this.setPath(`${this.path}/dice-3.svg`))
      .addSvgIcon("dice-4", this.setPath(`${this.path}/dice-4.svg`))
      .addSvgIcon("dice-5", this.setPath(`${this.path}/dice-5.svg`))
      .addSvgIcon("dice-6", this.setPath(`${this.path}/dice-6.svg`))
      .addSvgIcon("dock-bottom", this.setPath(`${this.path}/dock-bottom.svg`))
      .addSvgIcon("dock-left", this.setPath(`${this.path}/dock-left.svg`))
      .addSvgIcon("dock-right", this.setPath(`${this.path}/dock-right.svg`))
      .addSvgIcon("dock-window", this.setPath(`${this.path}/dock-window.svg`))
      .addSvgIcon("dollar", this.setPath(`${this.path}/dollar.svg`))
      .addSvgIcon("eject", this.setPath(`${this.path}/eject.svg`))
      .addSvgIcon("ericsson", this.setPath(`${this.path}/ericsson.svg`))
      .addSvgIcon("ethernet", this.setPath(`${this.path}/ethernet.svg`))
      .addSvgIcon("euro", this.setPath(`${this.path}/euro.svg`))
      .addSvgIcon("extension-add", this.setPath(`${this.path}/extension-add.svg`))
      .addSvgIcon("extension-alt", this.setPath(`${this.path}/extension-alt.svg`))
      .addSvgIcon("extension-remove", this.setPath(`${this.path}/extension-remove.svg`))
      .addSvgIcon("extension", this.setPath(`${this.path}/extension.svg`))
      .addSvgIcon("external", this.setPath(`${this.path}/external.svg`))
      .addSvgIcon("eye-alt", this.setPath(`${this.path}/eye-alt.svg`))
      .addSvgIcon("eye", this.setPath(`${this.path}/eye.svg`))
      .addSvgIcon("filters", this.setPath(`${this.path}/filters.svg`))
      .addSvgIcon("flag-alt", this.setPath(`${this.path}/flag-alt.svg`))
      .addSvgIcon("gender-female", this.setPath(`${this.path}/gender-female.svg`))
      .addSvgIcon("gender-male", this.setPath(`${this.path}/gender-male.svg`))
      .addSvgIcon("ghost-character", this.setPath(`${this.path}/ghost-character.svg`))
      .addSvgIcon("gift", this.setPath(`${this.path}/gift.svg`))
      .addSvgIcon("girl", this.setPath(`${this.path}/girl.svg`))
      .addSvgIcon("glass-alt", this.setPath(`${this.path}/glass-alt.svg`))
      .addSvgIcon("glass", this.setPath(`${this.path}/glass.svg`))
      .addSvgIcon("globe-alt", this.setPath(`${this.path}/globe-alt.svg`))
      .addSvgIcon("globe", this.setPath(`${this.path}/globe.svg`))
      .addSvgIcon("gym", this.setPath(`${this.path}/gym.svg`))
      .addSvgIcon("heart", this.setPath(`${this.path}/heart.svg`))
      .addSvgIcon("home-alt", this.setPath(`${this.path}/home-alt.svg`))
      .addSvgIcon("home", this.setPath(`${this.path}/home.svg`))
      .addSvgIcon("icecream", this.setPath(`${this.path}/icecream.svg`))
      .addSvgIcon("infinity", this.setPath(`${this.path}/infinity.svg`))
      .addSvgIcon("insights", this.setPath(`${this.path}/insights.svg`))
      .addSvgIcon("key", this.setPath(`${this.path}/key.svg`))
      .addSvgIcon("keyhole", this.setPath(`${this.path}/keyhole.svg`))
      .addSvgIcon("loadbar-alt", this.setPath(`${this.path}/loadbar-alt.svg`))
      .addSvgIcon("loadbar-doc", this.setPath(`${this.path}/loadbar-doc.svg`))
      .addSvgIcon("loadbar-sound", this.setPath(`${this.path}/loadbar-sound.svg`))
      .addSvgIcon("loadbar", this.setPath(`${this.path}/loadbar.svg`))
      .addSvgIcon("loupe", this.setPath(`${this.path}/loupe.svg`))
      .addSvgIcon("magnet", this.setPath(`${this.path}/magnet.svg`))
      .addSvgIcon("mail-forward", this.setPath(`${this.path}/mail-forward.svg`))
      .addSvgIcon("mail-open", this.setPath(`${this.path}/mail-open.svg`))
      .addSvgIcon("mail-replay", this.setPath(`${this.path}/mail-replay.svg`))
      .addSvgIcon("mail", this.setPath(`${this.path}/mail.svg`))
      .addSvgIcon("maximize-alt", this.setPath(`${this.path}/maximize-alt.svg`))
      .addSvgIcon("maximize", this.setPath(`${this.path}/maximize.svg`))
      .addSvgIcon("menu-cake", this.setPath(`${this.path}/menu-cake.svg`))
      .addSvgIcon("menu-cheese", this.setPath(`${this.path}/menu-cheese.svg`))
      .addSvgIcon("menu-grid-o", this.setPath(`${this.path}/menu-grid-o.svg`))
      .addSvgIcon("menu-grid-r", this.setPath(`${this.path}/menu-grid-r.svg`))
      .addSvgIcon("menu-hotdog", this.setPath(`${this.path}/menu-hotdog.svg`))
      .addSvgIcon("menu-motion", this.setPath(`${this.path}/menu-motion.svg`))
      .addSvgIcon("menu-oreos", this.setPath(`${this.path}/menu-oreos.svg`))
      .addSvgIcon("mini-player", this.setPath(`${this.path}/mini-player.svg`))
      .addSvgIcon("modem", this.setPath(`${this.path}/modem`))
      .addSvgIcon("moon", this.setPath(`${this.path}/moon.svg`))
      .addSvgIcon("nametag", this.setPath(`${this.path}/nametag.svg`))
      .addSvgIcon("notifications", this.setPath(`${this.path}/notifications.svg`))
      .addSvgIcon("open-collective", this.setPath(`${this.path}/open-collective.svg`))
      .addSvgIcon("options", this.setPath(`${this.path}/options.svg`))
      .addSvgIcon("organisation", this.setPath(`${this.path}/organisation.svg`))
      .addSvgIcon("password", this.setPath(`${this.path}/apassword.svg`))
      .addSvgIcon("performance", this.setPath(`${this.path}/performance.svg`))
      .addSvgIcon("pill", this.setPath(`${this.path}/pill.svg`))
      .addSvgIcon("plug", this.setPath(`${this.path}/plug.svg`))
      .addSvgIcon("profile", this.setPath(`${this.path}/profile.svg`))
      .addSvgIcon("pull-clear", this.setPath(`${this.path}/pull-clear.svg`))
      .addSvgIcon("radio-check", this.setPath(`${this.path}/radio-check.svg`))
      .addSvgIcon("radio-checkt", this.setPath(`${this.path}/radio-checkt.svg`))
      .addSvgIcon("readme", this.setPath(`${this.path}/readme.svg`))
      .addSvgIcon("record", this.setPath(`${this.path}/record.svg`))
      .addSvgIcon("remove-r", this.setPath(`${this.path}/remove-r.svg`))
      .addSvgIcon("remove", this.setPath(`${this.path}/remove.svg`))
      .addSvgIcon("reorder", this.setPath(`${this.path}/reorder.svg`))
      .addSvgIcon("ring", this.setPath(`${this.path}/ring.svg`))
      .addSvgIcon("sand-clock", this.setPath(`${this.path}/sand-clock.svg`))
      .addSvgIcon("scan", this.setPath(`${this.path}/scan.svg`))
      .addSvgIcon("search-found", this.setPath(`${this.path}/search-found.svg`))
      .addSvgIcon("search-loading", this.setPath(`${this.path}/search-loading.svg`))
      .addSvgIcon("search", this.setPath(`${this.path}/search.svg`))
      .addSvgIcon("shopping-bag", this.setPath(`${this.path}/shopping-bag.svg`))
      .addSvgIcon("shopping-cart", this.setPath(`${this.path}/shopping-cart.svg`))
      .addSvgIcon("sidebar-open", this.setPath(`${this.path}/sidebar-open.svg`))
      .addSvgIcon("sidebar-right", this.setPath(`${this.path}/sidebar-right.svg`))
      .addSvgIcon("sidebar", this.setPath(`${this.path}/sidebar.svg`))
      .addSvgIcon("sleep", this.setPath(`${this.path}/sleep.svg`))
      .addSvgIcon("smart-home-boiler", this.setPath(`${this.path}/smart-home-boiler.svg`))
      .addSvgIcon("smart-home-cooker", this.setPath(`${this.path}/smart-home-cooker.svg`))
      .addSvgIcon("smart-home-heat", this.setPath(`${this.path}/smart-home-heat.svg`))
      .addSvgIcon("smart-home-light", this.setPath(`${this.path}/smart-home-light.svg`))
      .addSvgIcon("smart-home-refrigerator", this.setPath(`${this.path}/smart-home-refrigerator.svg`))
      .addSvgIcon("smart-home-wash-machine", this.setPath(`${this.path}/smart-home-wash-machine.svg`))
      .addSvgIcon("space-between-v", this.setPath(`${this.path}/space-between-v.svg`))
      .addSvgIcon("space-between", this.setPath(`${this.path}/space-between.svg`))
      .addSvgIcon("spinner-alt", this.setPath(`${this.path}/spinner-alt.svg`))
      .addSvgIcon("spinner-two-alt", this.setPath(`${this.path}/spinner-two-alt.svg`))
      .addSvgIcon("spinner-two", this.setPath(`${this.path}/spinner-two.svg`))
      .addSvgIcon("spinner", this.setPath(`${this.path}/spinner.svg`))
      .addSvgIcon("style", this.setPath(`${this.path}/style.svg`))
      .addSvgIcon("sun", this.setPath(`${this.path}/sun.svg`))
      .addSvgIcon("support", this.setPath(`${this.path}/support.svg`))
      .addSvgIcon("tab", this.setPath(`${this.path}/tab.svg`))
      .addSvgIcon("tag", this.setPath(`${this.path}/tag.svg`))
      .addSvgIcon("tap-double", this.setPath(`${this.path}/tap-double.svg`))
      .addSvgIcon("tap-single", this.setPath(`${this.path}/tap-single.svg`))
      .addSvgIcon("tennis", this.setPath(`${this.path}/tennis.svg`))
      .addSvgIcon("terrain", this.setPath(`${this.path}/terrain.svg`))
      .addSvgIcon("thermometer", this.setPath(`${this.path}/thermometer.svg`))
      .addSvgIcon("time", this.setPath(`${this.path}/time.svg`))
      .addSvgIcon("timelapse", this.setPath(`${this.path}/timelapse.svg`))
      .addSvgIcon("timer", this.setPath(`${this.path}/timer.svg`))
      .addSvgIcon("today", this.setPath(`${this.path}/today.svg`))
      .addSvgIcon("track", this.setPath(`${this.path}/track.svg`))
      .addSvgIcon("transcript", this.setPath(`${this.path}/transcript.svg`))
      .addSvgIcon("tree", this.setPath(`${this.path}/tree.svg`))
      .addSvgIcon("trees", this.setPath(`${this.path}/trees.svg`))
      .addSvgIcon("trophy", this.setPath(`${this.path}/trophy.svg`))
      .addSvgIcon("umbrella", this.setPath(`${this.path}/umbrella.svg`))
      .addSvgIcon("unavailable", this.setPath(`${this.path}/unavailable.svg`))
      .addSvgIcon("unblock", this.setPath(`${this.path}/unblock.svg`))
      .addSvgIcon("user-add", this.setPath(`${this.path}/user-add.svg`))
      .addSvgIcon("user-list", this.setPath(`${this.path}/user-list.svg`))
      .addSvgIcon("user-remove", this.setPath(`${this.path}/user-remove.svg`))
      .addSvgIcon("user", this.setPath(`${this.path}/user.svg`))
      .addSvgIcon("vinyl", this.setPath(`${this.path}/vinyl.svg`))
      .addSvgIcon("work-alt", this.setPath(`${this.path}/work-alt.svg`))
      .addSvgIcon("yingyang", this.setPath(`${this.path}/yingyang.svg`))
      .addSvgIcon("zoom-in", this.setPath(`${this.path}/zoom-in.svg`))
      .addSvgIcon("zoom-out", this.setPath(`${this.path}/zoom-out.svg`))
      .addSvgIcon("menu-up", this.setPath(`${this.path}/menu-up.svg`))
      .addSvgIcon("menu-down", this.setPath(`${this.path}/menu-down.svg`))
      .addSvgIcon("star", this.setPath(`${this.path}/star.svg`))
      .addSvgIcon("star-half", this.setPath(`${this.path}/star-half.svg`))
      .addSvgIcon("thumb-down-outline", this.setPath(`${this.path}/thumb-down-outline.svg`))
      .addSvgIcon("thumb-up-outline", this.setPath(`${this.path}/thumb-up-outline.svg`))
      .addSvgIcon("star-outline", this.setPath(`${this.path}/star-outline.svg`))
      .addSvgIcon("message", this.setPath(`${this.path}/message.svg`))
      .addSvgIcon("message-outline", this.setPath(`${this.path}/message-outline.svg`))

  }
  private setPath(url: string): SafeResourceUrl {
    return this.domSanitizer.bypassSecurityTrustResourceUrl(url);
  }
}
